version: "3.8"
services:
  bot:
    build: .
    container_name: axo-nodes-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./backups:/app/backups
      - ./cache:/app/cache
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: host
    privileged: true
